# Generated by Django 5.2.3 on 2025-06-30 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id_descuento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('monto', models.FloatField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id_maquina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='maquinas/')),
                ('razon_inactividad', models.CharField(choices=[('reparacion', 'En Reparación'), ('mal_estado', 'Mal Estado'), ('mantenimiento', 'Mantenimiento Preventivo'), ('otra', 'Otra Razón'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=20)),
                ('fecha_inactividad', models.DateField(blank=True, null=True)),
                ('notas_inactividad', models.TextField(blank=True, null=True)),
                ('fecha_estimada_reparacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, max_length=25, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('existencia', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Barra energetica', 'Barra energética'), ('Proteina', 'Proteína'), ('Vitaminas', 'Vitaminas'), ('Suplementos', 'Suplementos'), ('Bebidas', 'Bebidas'), ('Caramelos', 'Caramelos')], default='suplementos', max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado')], default='Disponible', max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMembresia',
            fields=[
                ('id_membresia', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMembresia', models.CharField(blank=True, max_length=30, null=True)),
                ('duracionDias', models.IntegerField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='', max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True, null=True)),
                ('estudiante', models.CharField(blank=True, max_length=20, null=True)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='usuarios.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='usuarios.empleado')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='main.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Membresia', 'Membresía'), ('Producto', 'Producto')], default='Membresia', max_length=10)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('total_a_pagar', models.FloatField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='main.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PagoDescuento',
            fields=[
                ('id_pago_descuento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_aplicacion', models.DateField(auto_now_add=True)),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_aplicados', to='main.descuento')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_aplicados', to='main.pago')),
            ],
        ),
        migrations.CreateModel(
            name='PagoProducto',
            fields=[
                ('id_pago_producto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productospagados', to='main.pago')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='main.producto')),
            ],
        ),
        migrations.CreateModel(
            name='MembresiaCliente',
            fields=[
                ('id_membresia_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_cliente', to='main.cliente')),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_cliente', to='main.tipomembresia')),
            ],
        ),
    ]
