# Generated by Django 5.1.7 on 2025-03-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Barra energetica', 'Barra energética'), ('proteina', 'Proteína'), ('vitaminas', 'Vitaminas'), ('suplementos', 'Suplementos'), ('bebidas', 'Bebidas'), ('caramelos', 'Caramelos')], default='suplementos', max_length=20),
        ),
    ]
