# Generated by Django 5.2.3 on 2025-06-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_pago_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='checkin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='checkout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
