from django.db import migrations

def crear_membresias(apps, schema_editor):
    TipoMembresia = apps.get_model('main', 'TipoMembresia')  # Obtén el modelo Membresia
    TipoMembresia.objects.create(nombreMembresia="Mensual", precio=500, duracionDias=31)
    TipoMembresia.objects.create(nombreMembresia="Quincenal", precio=350, duracionDias=15)
    TipoMembresia.objects.create(nombreMembresia="Semanal", precio=200, duracionDias=7)
    TipoMembresia.objects.create(nombreMembresia="Diaria", precio=40, duracionDias=1)

def eliminar_membresias(apps, schema_editor):
    TipoMembresia = apps.get_model('main', 'TipoMembresia')  # Obtén el modelo Membresia
    TipoMembresia.objects.filter(nombreMembresia__in=["Mensual", "Quincenal", "Semanal", "Diaria"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_producto_tipo'),
    ]

    operations = [
        migrations.RunPython(crear_membresias, eliminar_membresias),  # Llama a la función para crear las membresías
    ]
# Generated by Django 5.1.7 on 2025-04-08 17:00

from django.db import migrations

def crear_membresias(apps, schema_editor):
    TipoMembresia = apps.get_model('main', 'TipoMembresia')  # Obtén el modelo Membresia
    TipoMembresia.objects.create(nombreMembresia="Mensual", precio=500, duracionDias=31)
    TipoMembresia.objects.create(nombreMembresia="Quincenal", precio=350, duracionDias=15)
    TipoMembresia.objects.create(nombreMembresia="Semanal", precio=200, duracionDias=7)
    TipoMembresia.objects.create(nombreMembresia="Diaria", precio=40, duracionDias=1)

def eliminar_membresias(apps, schema_editor):
    TipoMembresia = apps.get_model('main', 'TipoMembresia')  # Obtén el modelo Membresia
    TipoMembresia.objects.filter(nombreMembresia__in=["Mensual", "Quincenal", "Semanal", "Diaria"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_producto_tipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membresia',
            new_name='TipoMembresia',
        ),
        # Renombra los campos en el modelo TipoMembresia
        migrations.RenameField(
            model_name='tipomembresia',
            old_name='duracion',
            new_name='duracionDias',
        ),
        migrations.RenameField(
            model_name='tipomembresia',
            old_name='nombre',
            new_name='nombreMembresia',
        ),
        migrations.RunPython(crear_membresias, eliminar_membresias),
]