# Generated by Django 5.1.7 on 2025-04-12 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20250408_1100'),
    ]

    operations = [
        # Renombra el modelo Membresia a TipoMembresia primero
        migrations.RenameModel(
            old_name='Membresia',
            new_name='TipoMembresia',
        ),
        # Renombra los campos en el modelo TipoMembresia
        migrations.RenameField(
            model_name='tipomembresia',
            old_name='duracion',
            new_name='duracionDias',
        ),
        migrations.RenameField(
            model_name='tipomembresia',
            old_name='nombre',
            new_name='nombreMembresia',
        ),
        # Elimina campos del modelo Cliente
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='membresia',
        ),
        # Agrega un nuevo campo al modelo Cliente
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        # Crea el modelo MembresiaCliente
        migrations.CreateModel(
            name='MembresiaCliente',
            fields=[
                ('id_membresia_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_cliente', to='main.cliente')),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_cliente', to='main.tipomembresia')),
            ],
        ),
    ]