# Generated by Django 5.1.7 on 2025-05-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tipos_membresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
    ]
