# Generated by Django 5.1.7 on 2025-05-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_usuario_intentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='intentos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='n_intentos',
            field=models.IntegerField(default=0),
        ),
    ]
