# Generated by Django 5.1.7 on 2025-05-25 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_usuario_intentos_usuario_n_intentos'),
    ]

    operations = [
    ]
